config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  # root "users#home"

  root 'users#index'

  # resources :users, only: [:index, :show] do 
  #   resources :posts, only: [:index, :show, :new, :create, :destroy] do 
  #     resources :comments, only: [:new, :create, :destroy]
  #     resources :likes, only: [:index, :create]
  #   end
  # end

  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:index, :create]
    end
  end
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do 
        resources :posts, only: [:index, :show, :new, :create, :destroy] do 
          resources :comments, only: [:index,:new, :create, :destroy]
          resources :likes, only: [:index, :create]
        end
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]

  # GET /users
  def index
    @users = User.all
    # render json: @bands.includes(:members), only: [:name]
    render json: @users
  end

  # GET /users/id
  def show
    render json: @users
  end

  # POST /users
  def create
    @users = User.new(user_params)

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/id
  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/id
  def destroy
    @user.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :photo, :bio)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts).order(created_at: :asc)
  end

  def show
    @user = User.includes(:posts, :comments).find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.html.erb
<div class="bio">
  <h4>Bio</h4>
  <p><%= @user.bio %></p>
</div>

app/views/users/_post.html.erb
<li class="post">
  <h4 class="small-heading">
    <%= link_to "Post ##{post.id}", user_post_path(post.author_id, post.id) %>
  </h4>
  <% if post.text.present? && post.text.length > 200 %>
    <p><%= post.text.first(150)... %></p>
  <% else %>
    <p><%= post.text %></p>
  <% end %>
  <p class="comment-heading">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter %></p>
</li>

app/views/users/_user.html.erb
<li class="user">
    <div>
      <img src="<%= user.photo %>" alt="<%= user.name %>" >
    </div>
    <div class="user-details">
        <div class="heading-container">
            <h4 class="medium-heading">
            <%= link_to user.name, user_path(user.id) %>
            </h4>
        </div>
        <div class="post-counter-details">
        <p>Number of posts: <%= user.posts_counter %></p>
        </div>
    </div>
</li>

app/views/users/home.html.erb
<section>
Home
</section>

app/views/users/index.html.erb
<section class="section">

<ul>
  <% @users.each do |user| %>
    <%= render 'user', user: user%>
  <% end %>
</ul>
</section>

app/views/users/show.html.erb
<head>
  <%= stylesheet_link_tag 'style' %>
</head>

<section class="section">

<% if @user.nil? %>
  <h4>User not found</h4>
<% else %>
<div>
  <%= render 'user', user: @user %>
<div>

<%= render 'bio' %>

<ul>
<% @user.three_most_recent_posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>
</ul>

<div class="button">
  <button type="button"><%= link_to "See all posts", user_posts_path(user_id: @user.id) %></button>
</div>
<% end %>

</section>