config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  # root "users#home"

  root 'users#index'

  # resources :users, only: [:index, :show] do 
  #   resources :posts, only: [:index, :show, :new, :create, :destroy] do 
  #     resources :comments, only: [:new, :create, :destroy]
  #     resources :likes, only: [:index, :create]
  #   end
  # end

  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:index, :create]
    end
  end
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do 
        resources :posts, only: [:index, :show, :new, :create, :destroy] do 
          resources :comments, only: [:index,:new, :create, :destroy]
          resources :likes, only: [:index, :create]
        end
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :increment_user_posts_counter

  after_destroy :decrement_user_posts_counter

  validates :text, :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, presence: true,
                                               numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_user_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: %i[show update destroy]

  # GET /users/:user_id/posts
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    render json: @posts
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'User not found' }, status: :not_found
  rescue StandardError => e
    render json: { error: e.message }, status: :internal_server_error
  end

  # GET /users/:user_id/posts/:id
  def show
    render json: @post
  end

  # POST /users/:user_id/posts
  def create
    @post = Post.new(post_params)

    if @post.save
      render json: @post, status: :created, location: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/:user_id/posts/:id
  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/:user_id/posts/:id
  def destroy
    @post.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:text, :title)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    # @posts = Post.where(author_id: params[:user_id])
    # @user = User.find(params[:user_id])

    @user = User.includes(:posts, posts: [:comments]).find(params[:user_id])
    # @posts = @user.posts
  end

  def show
    # @post = Post.includes(comments: [:author]).find_by(author_id: params[:user_id], id: params[:id])
    # @user = User.find(params[:user_id])

    @user = User.includes(posts: [:comments]).find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @user = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_url
    else
      flash.now[:error] = 'Error: Post could not be saved'
      render :new, locals: { post: @post }
    end
  end

  def destroy
    @post.destroy
    redirect_to user_posts_path(params[:user_id]), notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).merge(author: current_user)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<div class="comments-container">
  <p class="comment"><%= comment.author.name %> : <%= comment.text %></p>


  <% if can? :destroy, comment %>
  <%= link_to "Delete", user_post_comment_path(@post.author.id, @post.id, comment.id), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }
  %>
<% end %>

</div>

app/views/posts/_form.html.erb
<%= bootstrap_form_with(model: @like, url: user_post_likes_path(@post.author_id, @post), local: true, layout: :horizontal) do |form| %>
      <%= form.button "Like"%>
  <% end %>

app/views/posts/_form_delete.html.erb
<%= bootstrap_form_with(model: @post, url: "/users/#{@user.id}/posts/", layout: :horizontal, method: :delete ) do |form| %>
    <%= form.button "Delete"%>
<% end %>

app/views/posts/_form_like.html.erb
<%= bootstrap_form_with(model: @like, url: user_post_likes_path(@post.author_id, @post), local: true, layout: :horizontal) do |form| %>
      <%= form.button "Like"%>
  <% end %>

app/views/posts/_post.html.erb
<div class="post">
    <h4 class="small-heading">
        Post #<%= @post.id %> by <%= @user.name %>
    </h4>
    <p class="comment-heading">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    <%= render 'form' %>
    <p><%= @post.text %></p>
</div>

app/views/posts/index.html.erb
<section class="section">

<% if @user.nil? %>
<h4>User not found</h4>
<% else %>
<div>
<%= render partial: 'users/user', locals: { user: @user } %>
<div>
<% end %>

<div class="button">
  <button type="button"><%= link_to 'add new post', new_user_post_path %></button>
</div>

<ul>
<% @user.posts.each do |post| %>
  <li >
  
  <li class="post">
  <h4 class="small-heading">
    <%= link_to "Post ##{post.id}", user_post_path(post.author_id, post.id) %>
  </h4>

  <% if can? :destroy, post %>
             <%= button_to 'delete post', user_post_path(post.author, post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <% if post.text.present? && post.text.length > 200 %>
    <p><%= post.text.first(150)... %></p>
  <% else %>
    <p><%= post.text %></p>
  <% end %>
  <p class="comment-heading">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter %></p>

  <%= button_to 'More', user_post_path(post.author_id, post.id), method: :get %>

</li>

  <% if post.comments_counter > 0 %>
          <% post.five_most_recent_comments.each do |comment| %>
            
            <div class="comments-container">
            <p class="comment"><%= comment.author.name %> : <%= comment.text %></p>
          </div>

            <% end %>
          <% end %>
  </li>
  <% end %>
</ul>
</section>

app/views/posts/new.html.erb
<section class="add-post-section flex-center">

<%= bootstrap_form_with(model: @post, url: user_posts_path, layout: :horizontal) do |form| %>
    <br>
    <%= form.text_field :title %>
    <br>
    <%= form.text_area :text %>
    <br>
    <%= form.button "Add Post" %>
    <% end %>
    
</section>

app/views/posts/show.html.erb
<section class="section">

<div class="button">
<button type="button">
<%= link_to "Add a comment", new_user_post_comment_path(@user, @post) %>
</button>
</div>

<%= render 'post', post: @post %>

<% if @post.comments.empty?%>
    <h4>No comments for this post</h4>
 <% else %>

          <% @post.comments.each do |comment| %>
            
            

            <div class="comments-container">
            <p class="comment"><%= comment.author.name %> : <%= comment.text %></p>
          
          
            <% if can? :destroy, comment %>
                        <%= button_to 'Delete comment', user_post_comment_path(comment.author, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                     <% end %>
          
          </div>

            <% end %>
    <% end %>
</section>